## ---------------------------------------------------------------------------
## Licensed to the Apache Software Foundation (ASF) under one or more
## contributor license agreements.  See the NOTICE file distributed with
## this work for additional information regarding copyright ownership.
## The ASF licenses this file to You under the Apache License, Version 2.0
## (the "License"); you may not use this file except in compliance with
## the License.  You may obtain a copy of the License at
##
## http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
## ---------------------------------------------------------------------------

admin = ENC(1024:BAC597A9015F66DE34D6E80E68526929809A088A28D99BBF5DAE78C3A50ABC64:1F783192AE09FFE5EF8FCBDDCA7C0FEA42568B9932E2DDC2A4F3A0C467957A44F08DB91EE352D655C0E2C1DF7BC1BD3F7C124D08BBEBF8D3824F567FA46B0717)
amq = amq
tester = tester
user = user